### ISSUE TITLE
Improve documentation of parameter start_first

### ISSUE THREAD

**Issue by kirrmann** [etlweather/gaucho#15]
`docker run --rm -e CATTLE_URL=http://test:8080/v1 -e CATTLE_ACCESS_KEY=123 -e CATTLE_SECRET_KEY=234 -it etlweather/gaucho upgrade 1s126 --start_first --auto_complete --complete_previous`

Setting start_first as parameter doesn't work, the container is instantly stopped and then started. There is no output which shows any errors for start_first. Upgrade is successfully finished. 

I'm using Rancher v1.4.1

**Comment by etlweather** [comment]
The docs isn't super clear on that, but can you try:

```
docker run --rm -e CATTLE_URL=http://test:8080/v1 -e CATTLE_ACCESS_KEY=123 -e CATTLE_SECRET_KEY=234 -it etlweather/gaucho upgrade 1s126 --start_first=True --auto_complete=True --complete_previous=True
```

**Comment by kirrmann** [comment]
Ok setting the start_first parameter to True does work. But auto_complete and complete_previous doesn't need to be set to True.

**Comment by etlweather** [comment]
Thanks. I'll update the Docs to be clearer (or make it that both form work...)
