### ISSUE TITLE
Upgrade service with sidekick

### ISSUE THREAD

**Issue by mjablecnik** [etlweather/gaucho#20]
Hello how can I with gaucho upgrade service also with sidekick??
When I run: `gaucho upgrade 1s137` it upgrade only one container:
![screenshot](https://user-images.githubusercontent.com/2686906/31669908-acd655ac-b356-11e7-8c6c-993673e4a733.png)

**Comment by etlweather** [comment]
Hum, I hadn't had to do this myself so never looked into it. If you can check the API, see what is there to cause the upgrade of the sidekick...

**Comment by duduti** [comment]
In line 141, you forgot "secondaryLaunchConfigs" attributes. 

`# Stuff the current service launch config into the request for upgrade
   upgrade_strategy['inServiceStrategy']['launchConfig'] = current_service_config['launchConfig']
   upgrade_strategy['inServiceStrategy']['secondaryLaunchConfigs'] = current_service_config['secondaryLaunchConfigs']`  #_**[NEW LINE]**_`

**Comment by etlweather** [comment]
I was away for a while, but I'm back. Thanks @duduti for the tip. @Applemann if you want to make the change, I'll be happy to merge it. I personally don't need this functionality at the moment so I won't have time to add this and test that in the next few weeks.
