### ISSUE TITLE
Suggestion: Why not Alpine python image?

### ISSUE THREAD

**Issue by MichelDiz** [etlweather/gaucho#25]
The image will be significantly smaller, from 275 MB to just over 35 MB

https://hub.docker.com/r/library/python/tags/

`python:2.7-alpine`

```dockerfile
FROM python:alpine3.6

WORKDIR /app

RUN pip install \
        requests==2.18.4 \
        baker==1.3 \
        websocket-client==0.44.0

COPY services.py /app/gaucho
RUN chmod +x /app/gaucho

ENTRYPOINT ["/app/gaucho"]
```

**Comment by etlweather** [comment]
The only reason I haven't merge #9 is because I have a decedent image that will need re-testing... But let's look into this, I have some time today.

**Comment by etlweather** [comment]
There is a tag now for alpine: `etlweather/gaucho:alpine`
