### ISSUE TITLE
Is there any way to finish upgrade of a service which state is upgraded?

### ISSUE THREAD

**Issue by zot24** [etlweather/gaucho#28]
I can't find the way to `finish upgrade` of a service which state is `upgraded`

Thanks

**Comment by nimboya** [comment]
There is a finish upgrade API that you can call, delay for about 2 mins to allow the upgrade to be complete before initiating the finish upgrade call "?action=upgrade" with the launchConfig accordingly

**Comment by etlweather** [comment]
Do you mean: once the upgrade is completed, call the finish upgrade?

If so, the auto-complete flag is what you are looking for:

https://github.com/etlweather/gaucho#upgrade

```
   --auto_complete      Set this to automatically 'finish upgrade' once
                        upgrade is complete
```

**Comment by etlweather** [comment]
But if you mean as a separate call, then it will need to be added but that should be simple.

**Comment by nimboya** [comment]
Glad to contribute Or I am sure you are adding that right ?

**Comment by zot24** [comment]
> But if you mean as a separate call, then it will need to be added but that should be simple.

Yep that's what I meant @etlweather thought I was missing something good to know it's not there yet

Thanks,
