### ISSUE TITLE
override for services in the state updating-active

### ISSUE THREAD

**Issue by junkiebev** [etlweather/gaucho#31]
For services that are flapping (and thus never initialize), issuing a command to update the service results in the following error
```
Service cannot be updated due to its current state: updating-active
```
Is there any way to add an argument which allows an upgrade? In the UI, you'd do that by stopping the service and then upgrading it.

**Comment by etlweather** [comment]
Hi there!

This is definitely a valid point. 

Unfortunately, I no longer use Rancher 1.x and moved everything to Rancher 2/Kubernetes.

So I won't really be doing any maintenance to this project at this point.

**Comment by junkiebev** [comment]
I'm doing that too - Just thought I'd ping ya :)
